services:
    mu_transport_module.link_container:
        class: MU\TransportModule\Container\LinkContainer
        arguments:
            - "@translator.default"
            - "@router"
            - "@zikula_permissions_module.api.permission"
            - "@mu_transport_module.controller_helper"
        tags:
            - { name: zikula.link_container }
