services:
    # Twig extension
    mu_transport_module.twig_extension:
        class: MU\TransportModule\Twig\TwigExtension
        arguments:
            - "@translator.default"
            - "@zikula_extensions_module.api.variable"
            - "@mu_transport_module.entity_display_helper"
            - "@mu_transport_module.workflow_helper"
            - "@mu_transport_module.listentries_helper"
        public: false
        tags:
            - { name: twig.extension }
