services:
    # Custom validators
    mu_transport_module.validator.list_entry.validator:
        class: MU\TransportModule\Validator\Constraints\ListEntryValidator
        arguments:
            - "@translator.default"
            - "@mu_transport_module.listentries_helper"
        tags:
            - { name: validator.constraint_validator, alias: mu_transport_module.validator.list_entry.validator }
